bindAddr = "0.0.0.0"
bindPort = 7000
vhostHTTPPort = 7100

# https://gofrp.org/zh-cn/docs/features/http-https/subdomain/
# 服务端配置 subDomainHost 后，客户端可以不配置
# 国内使用自定义域名还是存在备案问题

subDomainHost = "valjean.cn"

#[auth]
#method = "token"
#token = "6517040aacfc4e0ad1e0bc01fd550a20837b89c5"
[log]
to = "/var/log/frps.log"
level = "debug"
maxDays = 3

#[sshTunnelGateway]
#bindPort = 7104


